-- ============================================
-- FIX NULL ASSIGNEES ON IMPORTED PROJECTS
-- Updates assignee for projects that were inserted without a freelancer.
-- Safe to run multiple times.
-- ============================================

UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'ARS 100001' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'ARS 100002' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100003' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100004' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100005' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100006' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'GHA 100007' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100008' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100009' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'ARS 100010' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100011' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'ARS 100012' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'ARS 100013' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'ARS 100014' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100015' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100016' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100017' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'ARS 100018' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100019' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100020' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100021' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100022' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100023' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100024' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'GHA 100025' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100026' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100027' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100028' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100029' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100030' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100031' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100032' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100033' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100034' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100035' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100036' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100037' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100038' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100039' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100040' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100041' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100042' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100043' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100044' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'ARS 100045' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100046' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100047' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'GHA 100048' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100049' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100050' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'ARS 100051' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'ARS 100052' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'GHA 100053' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100054' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'GHA 100055' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'ARS 100056' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100057' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100058' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100059' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100060' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100061' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100062' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100063' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100064' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100065' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100066' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100067' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100068' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100069' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100070' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100071' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100072' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100073' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100074' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100075' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100076' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100077' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100078' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100079' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100080' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100081' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100082' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100083' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100084' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100085' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Arsalan Hussain' WHERE project_id = 'MAN 100086' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'GHA 100087' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100088' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100089' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100090' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100091' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100092' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100093' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100094' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100095' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'ARS 100096' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100097' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100098' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100099' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100100' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100101' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100102' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100103' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100104' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100105' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100106' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100107' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100108' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'ARS 100109' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100110' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100111' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'GHA 100112' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100113' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100114' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100115' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100116' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100117' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100118' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100119' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100120' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100121' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100122' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100123' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100124' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100125' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100126' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100127' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100128' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100129' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100130' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100131' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100132' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100133' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100134' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100135' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100136' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100137' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100138' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100139' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100140' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100141' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100142' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100143' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100144' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100145' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100146' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100147' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100148' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100149' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100150' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100151' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100152' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100153' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100154' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100155' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100156' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100157' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100158' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100159' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100160' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100161' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100162' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100163' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100164' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100165' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100166' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Chetan Jhetwa' WHERE project_id = 'MAN 100167' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100168' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Syed Jawad Ul Hasan' WHERE project_id = 'MAN 100169' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100170' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100171' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100172' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Syed Jawad Ul Hasan' WHERE project_id = 'ARS 100173' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100174' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100175' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100176' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Touseef Ahmed' WHERE project_id = 'MAN 100177' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100178' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Zeeshan Alam' WHERE project_id = 'MAN 100179' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Muhammad Salman' WHERE project_id = 'MAN 100180' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100181' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Stephen' WHERE project_id = 'MAN 100182' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Muhammad Salman' WHERE project_id = 'MAN 100183' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Muhammad Salman' WHERE project_id = 'MAN 100184' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Muhammad Salman' WHERE project_id = 'MAN 100185' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Chetan Jhetwa' WHERE project_id = 'MAN 100186' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Chetan Jhetwa' WHERE project_id = 'MAN 100187' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Chetan Jhetwa' WHERE project_id = 'MAN 100188' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100189' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Taha Khan' WHERE project_id = 'MAN 100190' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Syed Jawad Ul Hasan' WHERE project_id = 'MAN 100191' AND (assignee IS NULL OR assignee = '');
UPDATE projects SET assignee = 'Syed Jawad Ul Hasan' WHERE project_id = 'MAN 100192' AND (assignee IS NULL OR assignee = '');

-- Total UPDATE statements: 192
