-- Auto-generated SQL insert queries from Excel


INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 591565', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'gregculver35', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    80, 
    'Mubashir Salman', 
    'Mubashir Salman', 
    'Approved', 
    '2025-12-12 00:00:00.000+00', 
    '2025-12-12 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'MAN 939619', 
    'Add', 
    'Logo Design', 
    'MAN', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'MAN' LIMIT 1), 
    'new', 
    'sanmagan', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Ranking', 
    10, 
    'Mubashir Salman', 
    NULL, 
    'Approved', 
    '2025-12-14 00:00:00.000+00', 
    '2025-12-14 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 551004', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'molllyyyyyyyy', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Ranking', 
    15, 
    'Mubashir Salman', 
    'Mubashir Salman', 
    'Approved', 
    '2025-12-15 00:00:00.000+00', 
    '2025-12-15 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 795366', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'kevinhennen506', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Ranking', 
    40, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-16 00:00:00.000+00', 
    '2025-12-16 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'ARS 427012', 
    'Add', 
    'Logo Design', 
    'ARS', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'ARS' LIMIT 1), 
    'new', 
    'finnoomen', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    40, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-16 00:00:00.000+00', 
    '2025-12-16 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 357189', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'sandragdel', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    20, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-19 00:00:00.000+00', 
    '2025-12-19 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'ARS 532553', 
    'Add', 
    'Logo Design', 
    'ARS', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'ARS' LIMIT 1), 
    'new', 
    'maxben9', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    25, 
    'Samad', 
    'Samad', 
    'Approved', 
    '2025-12-22 00:00:00.000+00', 
    '2025-12-22 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 632107', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'bashesho_17', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Ranking', 
    40, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-22 00:00:00.000+00', 
    '2025-12-22 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 729483', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'inter_team', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Ranking', 
    30, 
    'Samad', 
    'Samad', 
    'Approved', 
    '2025-12-24 00:00:00.000+00', 
    '2025-12-24 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'ARS 426469', 
    'Add', 
    'Logo Design', 
    'ARS', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'ARS' LIMIT 1), 
    'new', 
    'neorichi', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    30, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-26 00:00:00.000+00', 
    '2025-12-26 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'ARS 474488', 
    'Add', 
    'Logo Design', 
    'ARS', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'ARS' LIMIT 1), 
    'new', 
    'shurnymarengo', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    30, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-26 00:00:00.000+00', 
    '2025-12-26 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 339168', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'kevinkandil        ', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    25, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-28 00:00:00.000+00', 
    '2025-12-28 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 185635', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'djokoray', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    40, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-28 00:00:00.000+00', 
    '2025-12-28 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 950644', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'destucburen', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    30, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-29 00:00:00.000+00', 
    '2025-12-29 00:00:00.000+00'
);

INSERT INTO projects (
    project_id, 
    action_move, 
    project_title, 
    account, 
    account_id,
    client_type, 
    client_name, 
    items_sold, 
    addons, 
    medium, 
    price, 
    assignee, 
    converted_by, 
    status, 
    created_at, 
    updated_at
) VALUES (
    'GHA 602519', 
    'Add', 
    'Logo Design', 
    'GHA', 
    (SELECT id FROM accounts WHERE prefix ILIKE 'GHA' LIMIT 1), 
    'new', 
    'a_ridge', 
    '{"items":["Logo"]}', 
    '{"items":[]}', 
    'Repeat Buyer', 
    20, 
    'Zara Khan', 
    'Zara Khan', 
    'Approved', 
    '2025-12-30 00:00:00.000+00', 
    '2025-12-30 00:00:00.000+00'
);
